-- Asset Management Phase 1 schema (MySQL / MariaDB)
-- Safe to re-run: CREATE TABLE IF NOT EXISTS

CREATE TABLE IF NOT EXISTS `asset_locations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `parent_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `location_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `location_type` VARCHAR(60) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `campus` VARCHAR(120) NULL DEFAULT NULL,
  `building` VARCHAR(120) NULL DEFAULT NULL,
  `floor` VARCHAR(60) NULL DEFAULT NULL,
  `room` VARCHAR(60) NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=active 0=archived',
  `responsible_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_loc_school_code` (`school_id`, `location_code`),
  KEY `idx_asset_loc_parent` (`school_id`, `parent_location_id`),
  KEY `idx_asset_loc_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `parent_category_id` INT UNSIGNED NULL DEFAULT NULL,
  `category_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `asset_class` VARCHAR(40) NULL DEFAULT 'tangible' COMMENT 'tangible|intangible',
  `tracking_mode` VARCHAR(40) NULL DEFAULT 'individual' COMMENT 'individual|quantity',
  `is_fixed_asset` TINYINT(1) NOT NULL DEFAULT 1,
  `is_consumable` TINYINT(1) NOT NULL DEFAULT 0,
  `default_useful_life` INT NULL DEFAULT NULL COMMENT 'months',
  `default_depreciation_method` VARCHAR(40) NULL DEFAULT 'straight_line',
  `default_residual_percent` DECIMAL(8,2) NULL DEFAULT 0.00,
  `inspection_frequency_days` INT NULL DEFAULT NULL,
  `maintenance_frequency_days` INT NULL DEFAULT NULL,
  `requires_serial_number` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_rfid` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_barcode` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_warranty` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_cat_school_code` (`school_id`, `category_code`),
  KEY `idx_asset_cat_parent` (`school_id`, `parent_category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_category_fields` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `field_key` VARCHAR(80) NOT NULL,
  `field_label` VARCHAR(120) NOT NULL,
  `data_type` VARCHAR(40) NOT NULL DEFAULT 'text' COMMENT 'text|number|date|boolean|select',
  `options_json` TEXT NULL,
  `is_required` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_cat_field` (`category_id`, `field_key`),
  KEY `idx_acf_school_cat` (`school_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `assets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_code` VARCHAR(60) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `category_id` INT UNSIGNED NULL DEFAULT NULL,
  `location_id` INT UNSIGNED NULL DEFAULT NULL,
  `brand` VARCHAR(120) NULL DEFAULT NULL,
  `model` VARCHAR(120) NULL DEFAULT NULL,
  `manufacturer` VARCHAR(120) NULL DEFAULT NULL,
  `serial_number` VARCHAR(120) NULL DEFAULT NULL,
  `barcode` VARCHAR(120) NULL DEFAULT NULL,
  `rfid_tag` VARCHAR(120) NULL DEFAULT NULL,
  `part_number` VARCHAR(120) NULL DEFAULT NULL,
  `external_ref` VARCHAR(120) NULL DEFAULT NULL,
  `department` VARCHAR(120) NULL DEFAULT NULL,
  `cost_centre` VARCHAR(120) NULL DEFAULT NULL,
  `custodian_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `responsible_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `ownership_type` VARCHAR(60) NULL DEFAULT 'owned',
  `funding_source` VARCHAR(120) NULL DEFAULT NULL,
  `supplier` VARCHAR(180) NULL DEFAULT NULL,
  `purchase_date` DATE NULL DEFAULT NULL,
  `receipt_date` DATE NULL DEFAULT NULL,
  `commissioning_date` DATE NULL DEFAULT NULL,
  `purchase_price` DECIMAL(18,2) NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NULL DEFAULT 'RWF',
  `additional_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `total_acquisition_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `po_number` VARCHAR(80) NULL DEFAULT NULL,
  `invoice_number` VARCHAR(80) NULL DEFAULT NULL,
  `useful_life_months` INT NULL DEFAULT NULL,
  `residual_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `depreciation_method` VARCHAR(40) NULL DEFAULT 'straight_line',
  `depreciation_start_date` DATE NULL DEFAULT NULL,
  `accumulated_depreciation` DECIMAL(18,2) NULL DEFAULT 0.00,
  `net_book_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `replacement_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `condition_code` VARCHAR(40) NULL DEFAULT 'good',
  `lifecycle_status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `criticality` VARCHAR(40) NULL DEFAULT 'normal',
  `warranty_start` DATE NULL DEFAULT NULL,
  `warranty_expiry` DATE NULL DEFAULT NULL,
  `insurance_policy` VARCHAR(120) NULL DEFAULT NULL,
  `insurance_expiry` DATE NULL DEFAULT NULL,
  `last_inspection_date` DATE NULL DEFAULT NULL,
  `next_inspection_date` DATE NULL DEFAULT NULL,
  `last_maintenance_date` DATE NULL DEFAULT NULL,
  `next_maintenance_date` DATE NULL DEFAULT NULL,
  `quantity` DECIMAL(18,2) NOT NULL DEFAULT 1.00,
  `tracking_mode` VARCHAR(40) NOT NULL DEFAULT 'individual',
  `photo_path` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `custom_fields_json` LONGTEXT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `approved_by` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_assets_school_code` (`school_id`, `asset_code`),
  KEY `idx_assets_school_status` (`school_id`, `lifecycle_status`),
  KEY `idx_assets_location` (`school_id`, `location_id`),
  KEY `idx_assets_category` (`school_id`, `category_id`),
  KEY `idx_assets_custodian` (`school_id`, `custodian_staff_id`),
  KEY `idx_assets_serial` (`school_id`, `serial_number`),
  KEY `idx_assets_barcode` (`school_id`, `barcode`),
  KEY `idx_assets_rfid` (`school_id`, `rfid_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_status_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `previous_status` VARCHAR(40) NULL DEFAULT NULL,
  `new_status` VARCHAR(40) NOT NULL,
  `operation_type` VARCHAR(60) NOT NULL DEFAULT 'status_change',
  `actor_id` INT NULL DEFAULT NULL,
  `source_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `destination_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `previous_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `new_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `attachment_path` VARCHAR(255) NULL DEFAULT NULL,
  `approval_ref` VARCHAR(80) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ash_asset` (`asset_id`),
  KEY `idx_ash_school` (`school_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `code_pattern` VARCHAR(80) NOT NULL DEFAULT 'AST-{CATEGORY}-{YEAR}-{SEQ}',
  `seq_padding` INT NOT NULL DEFAULT 6,
  `default_currency` VARCHAR(10) NOT NULL DEFAULT 'RWF',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_settings_school` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Asset Management Phases 2–5 (imports, circulation, operations, finance)

CREATE TABLE IF NOT EXISTS `asset_imports` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `mode` VARCHAR(40) NOT NULL DEFAULT 'create_only' COMMENT 'create_only|create_update|validate_only',
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft' COMMENT 'draft|preview|committed|failed',
  `total_rows` INT NOT NULL DEFAULT 0,
  `valid_rows` INT NOT NULL DEFAULT 0,
  `warning_rows` INT NOT NULL DEFAULT 0,
  `error_rows` INT NOT NULL DEFAULT 0,
  `created_by` INT NULL DEFAULT NULL,
  `summary_json` LONGTEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_asset_imports_school` (`school_id`, `status`),
  KEY `idx_asset_imports_created` (`school_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_import_rows` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `import_id` INT UNSIGNED NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `row_number` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(40) NOT NULL DEFAULT 'valid' COMMENT 'valid|warning|error|imported',
  `asset_code` VARCHAR(60) NULL DEFAULT NULL,
  `payload_json` LONGTEXT NULL,
  `errors_json` LONGTEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_air_import` (`import_id`),
  KEY `idx_air_school` (`school_id`, `import_id`),
  KEY `idx_air_status` (`import_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_assignments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `staff_id` INT UNSIGNED NOT NULL,
  `role` VARCHAR(40) NOT NULL DEFAULT 'custodian' COMMENT 'custodian|owner|user|approver|auditor|maintenance',
  `assigned_at` DATETIME NULL DEFAULT NULL,
  `acknowledged_at` DATETIME NULL DEFAULT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active' COMMENT 'active|ended',
  `notes` TEXT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_aa_school_asset` (`school_id`, `asset_id`),
  KEY `idx_aa_staff` (`school_id`, `staff_id`),
  KEY `idx_aa_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_loans` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `borrower_type` VARCHAR(20) NOT NULL DEFAULT 'student' COMMENT 'student|staff',
  `borrower_id` INT UNSIGNED NOT NULL,
  `issued_by` INT NULL DEFAULT NULL,
  `issue_at` DATETIME NULL DEFAULT NULL,
  `due_at` DATETIME NULL DEFAULT NULL,
  `return_at` DATETIME NULL DEFAULT NULL,
  `issue_condition` VARCHAR(80) NULL DEFAULT NULL,
  `return_condition` VARCHAR(80) NULL DEFAULT NULL,
  `source_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `intended_use` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `penalty_amount` DECIMAL(18,2) NULL DEFAULT 0.00,
  `status` VARCHAR(40) NOT NULL DEFAULT 'open' COMMENT 'open|returned|overdue|lost|damaged',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_aloan_school_asset` (`school_id`, `asset_id`),
  KEY `idx_aloan_borrower` (`school_id`, `borrower_type`, `borrower_id`),
  KEY `idx_aloan_status` (`school_id`, `status`),
  KEY `idx_aloan_due` (`school_id`, `due_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_transfers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `transfer_no` VARCHAR(60) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft' COMMENT 'draft|pending_approval|approved|dispatched|completed|rejected|cancelled',
  `transfer_type` VARCHAR(40) NOT NULL DEFAULT 'location' COMMENT 'location|staff|department|campus',
  `is_temporary` TINYINT(1) NOT NULL DEFAULT 0,
  `from_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `to_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `from_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `to_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `approved_by` INT NULL DEFAULT NULL,
  `received_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_atransfer_school_no` (`school_id`, `transfer_no`),
  KEY `idx_atransfer_school_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_transfer_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transfer_id` INT UNSIGNED NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pending' COMMENT 'pending|accepted|rejected|missing|damaged',
  `notes` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ati_transfer` (`transfer_id`),
  KEY `idx_ati_school_asset` (`school_id`, `asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_maintenance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `work_order_no` VARCHAR(60) NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `maintenance_type` VARCHAR(40) NOT NULL DEFAULT 'corrective' COMMENT 'preventive|corrective|calibration',
  `problem` TEXT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'normal' COMMENT 'low|normal|high|critical',
  `requested_by` INT NULL DEFAULT NULL,
  `assigned_to` INT NULL DEFAULT NULL,
  `provider_type` VARCHAR(20) NULL DEFAULT 'internal' COMMENT 'internal|external',
  `scheduled_date` DATE NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `completion_date` DATE NULL DEFAULT NULL,
  `labour_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `parts_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `other_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `total_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `work_performed` TEXT NULL,
  `result` TEXT NULL,
  `next_maintenance_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'requested' COMMENT 'requested|approved|scheduled|in_progress|waiting_parts|completed|verified|cancelled',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_amaint_school_wo` (`school_id`, `work_order_no`),
  KEY `idx_amaint_school_asset` (`school_id`, `asset_id`),
  KEY `idx_amaint_status` (`school_id`, `status`),
  KEY `idx_amaint_scheduled` (`school_id`, `scheduled_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_inspections` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `inspected_by` INT NULL DEFAULT NULL,
  `inspection_date` DATE NULL DEFAULT NULL,
  `result` VARCHAR(40) NOT NULL DEFAULT 'pass' COMMENT 'pass|fail|conditional',
  `condition_code` VARCHAR(40) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `next_inspection_date` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ainsp_school_asset` (`school_id`, `asset_id`),
  KEY `idx_ainsp_date` (`school_id`, `inspection_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_incidents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `incident_no` VARCHAR(60) NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `reported_by` INT NULL DEFAULT NULL,
  `incident_at` DATETIME NULL DEFAULT NULL,
  `location_id` INT UNSIGNED NULL DEFAULT NULL,
  `incident_type` VARCHAR(40) NOT NULL DEFAULT 'damage' COMMENT 'damage|loss|theft|misuse|accident|safety|data_security|insurance',
  `description` TEXT NULL,
  `people_involved` TEXT NULL,
  `immediate_action` TEXT NULL,
  `estimated_loss` DECIMAL(18,2) NULL DEFAULT 0.00,
  `police_ref` VARCHAR(120) NULL DEFAULT NULL,
  `insurance_ref` VARCHAR(120) NULL DEFAULT NULL,
  `findings` TEXT NULL,
  `decision` TEXT NULL,
  `financial_recovery` DECIMAL(18,2) NULL DEFAULT 0.00,
  `status` VARCHAR(40) NOT NULL DEFAULT 'open' COMMENT 'open|investigating|resolved|closed',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ainc_school_no` (`school_id`, `incident_no`),
  KEY `idx_ainc_school_asset` (`school_id`, `asset_id`),
  KEY `idx_ainc_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_audits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `audit_no` VARCHAR(60) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft' COMMENT 'draft|in_progress|review|closed',
  `location_id` INT UNSIGNED NULL DEFAULT NULL,
  `category_id` INT UNSIGNED NULL DEFAULT NULL,
  `custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `snapshot_json` LONGTEXT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `closed_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `closed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_aaudit_school_no` (`school_id`, `audit_no`),
  KEY `idx_aaudit_school_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_audit_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `audit_id` INT UNSIGNED NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NULL DEFAULT NULL,
  `expected_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `found_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `result` VARCHAR(40) NOT NULL DEFAULT 'pending' COMMENT 'found_ok|wrong_location|wrong_custodian|damaged|not_found|unexpected|duplicate_tag|unregistered|pending|reconciled',
  `condition_code` VARCHAR(40) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `scanned_code` VARCHAR(120) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_aai_audit` (`audit_id`),
  KEY `idx_aai_school` (`school_id`, `audit_id`),
  KEY `idx_aai_result` (`audit_id`, `result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_disposals` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `disposal_no` VARCHAR(60) NOT NULL,
  `method` VARCHAR(40) NOT NULL DEFAULT 'write_off' COMMENT 'sale|donation|recycle|write_off',
  `status` VARCHAR(40) NOT NULL DEFAULT 'requested' COMMENT 'requested|approved|completed|rejected',
  `reason` TEXT NULL,
  `proceeds` DECIMAL(18,2) NULL DEFAULT 0.00,
  `requested_by` INT NULL DEFAULT NULL,
  `approved_by` INT NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_adisp_school_no` (`school_id`, `disposal_no`),
  KEY `idx_adisp_school_asset` (`school_id`, `asset_id`),
  KEY `idx_adisp_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_depreciation_entries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `period_ym` CHAR(7) NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `accumulated` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `net_book_value` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `method` VARCHAR(40) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ade_asset_period` (`school_id`, `asset_id`, `period_ym`),
  KEY `idx_ade_school_period` (`school_id`, `period_ym`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_location_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `from_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `to_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `moved_by` INT NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_alh_school_asset` (`school_id`, `asset_id`),
  KEY `idx_alh_created` (`school_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
