-- Asset Management Phase 1 schema (MySQL / MariaDB)
-- Safe to re-run: CREATE TABLE IF NOT EXISTS

CREATE TABLE IF NOT EXISTS `asset_locations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `parent_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `location_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `location_type` VARCHAR(60) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `campus` VARCHAR(120) NULL DEFAULT NULL,
  `building` VARCHAR(120) NULL DEFAULT NULL,
  `floor` VARCHAR(60) NULL DEFAULT NULL,
  `room` VARCHAR(60) NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=active 0=archived',
  `responsible_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_loc_school_code` (`school_id`, `location_code`),
  KEY `idx_asset_loc_parent` (`school_id`, `parent_location_id`),
  KEY `idx_asset_loc_status` (`school_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `parent_category_id` INT UNSIGNED NULL DEFAULT NULL,
  `category_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `asset_class` VARCHAR(40) NULL DEFAULT 'tangible' COMMENT 'tangible|intangible',
  `tracking_mode` VARCHAR(40) NULL DEFAULT 'individual' COMMENT 'individual|quantity',
  `is_fixed_asset` TINYINT(1) NOT NULL DEFAULT 1,
  `is_consumable` TINYINT(1) NOT NULL DEFAULT 0,
  `default_useful_life` INT NULL DEFAULT NULL COMMENT 'months',
  `default_depreciation_method` VARCHAR(40) NULL DEFAULT 'straight_line',
  `default_residual_percent` DECIMAL(8,2) NULL DEFAULT 0.00,
  `inspection_frequency_days` INT NULL DEFAULT NULL,
  `maintenance_frequency_days` INT NULL DEFAULT NULL,
  `requires_serial_number` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_rfid` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_barcode` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_warranty` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_cat_school_code` (`school_id`, `category_code`),
  KEY `idx_asset_cat_parent` (`school_id`, `parent_category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_category_fields` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `field_key` VARCHAR(80) NOT NULL,
  `field_label` VARCHAR(120) NOT NULL,
  `data_type` VARCHAR(40) NOT NULL DEFAULT 'text' COMMENT 'text|number|date|boolean|select',
  `options_json` TEXT NULL,
  `is_required` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_cat_field` (`category_id`, `field_key`),
  KEY `idx_acf_school_cat` (`school_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `assets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_code` VARCHAR(60) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `category_id` INT UNSIGNED NULL DEFAULT NULL,
  `location_id` INT UNSIGNED NULL DEFAULT NULL,
  `brand` VARCHAR(120) NULL DEFAULT NULL,
  `model` VARCHAR(120) NULL DEFAULT NULL,
  `manufacturer` VARCHAR(120) NULL DEFAULT NULL,
  `serial_number` VARCHAR(120) NULL DEFAULT NULL,
  `barcode` VARCHAR(120) NULL DEFAULT NULL,
  `rfid_tag` VARCHAR(120) NULL DEFAULT NULL,
  `part_number` VARCHAR(120) NULL DEFAULT NULL,
  `external_ref` VARCHAR(120) NULL DEFAULT NULL,
  `department` VARCHAR(120) NULL DEFAULT NULL,
  `cost_centre` VARCHAR(120) NULL DEFAULT NULL,
  `custodian_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `responsible_staff_id` INT UNSIGNED NULL DEFAULT NULL,
  `ownership_type` VARCHAR(60) NULL DEFAULT 'owned',
  `funding_source` VARCHAR(120) NULL DEFAULT NULL,
  `supplier` VARCHAR(180) NULL DEFAULT NULL,
  `purchase_date` DATE NULL DEFAULT NULL,
  `receipt_date` DATE NULL DEFAULT NULL,
  `commissioning_date` DATE NULL DEFAULT NULL,
  `purchase_price` DECIMAL(18,2) NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NULL DEFAULT 'RWF',
  `additional_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `total_acquisition_cost` DECIMAL(18,2) NULL DEFAULT 0.00,
  `po_number` VARCHAR(80) NULL DEFAULT NULL,
  `invoice_number` VARCHAR(80) NULL DEFAULT NULL,
  `useful_life_months` INT NULL DEFAULT NULL,
  `residual_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `depreciation_method` VARCHAR(40) NULL DEFAULT 'straight_line',
  `depreciation_start_date` DATE NULL DEFAULT NULL,
  `accumulated_depreciation` DECIMAL(18,2) NULL DEFAULT 0.00,
  `net_book_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `replacement_value` DECIMAL(18,2) NULL DEFAULT 0.00,
  `condition_code` VARCHAR(40) NULL DEFAULT 'good',
  `lifecycle_status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `criticality` VARCHAR(40) NULL DEFAULT 'normal',
  `warranty_start` DATE NULL DEFAULT NULL,
  `warranty_expiry` DATE NULL DEFAULT NULL,
  `insurance_policy` VARCHAR(120) NULL DEFAULT NULL,
  `insurance_expiry` DATE NULL DEFAULT NULL,
  `last_inspection_date` DATE NULL DEFAULT NULL,
  `next_inspection_date` DATE NULL DEFAULT NULL,
  `last_maintenance_date` DATE NULL DEFAULT NULL,
  `next_maintenance_date` DATE NULL DEFAULT NULL,
  `quantity` DECIMAL(18,2) NOT NULL DEFAULT 1.00,
  `tracking_mode` VARCHAR(40) NOT NULL DEFAULT 'individual',
  `photo_path` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `custom_fields_json` LONGTEXT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `approved_by` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `archived_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_assets_school_code` (`school_id`, `asset_code`),
  KEY `idx_assets_school_status` (`school_id`, `lifecycle_status`),
  KEY `idx_assets_location` (`school_id`, `location_id`),
  KEY `idx_assets_category` (`school_id`, `category_id`),
  KEY `idx_assets_custodian` (`school_id`, `custodian_staff_id`),
  KEY `idx_assets_serial` (`school_id`, `serial_number`),
  KEY `idx_assets_barcode` (`school_id`, `barcode`),
  KEY `idx_assets_rfid` (`school_id`, `rfid_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_status_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `previous_status` VARCHAR(40) NULL DEFAULT NULL,
  `new_status` VARCHAR(40) NOT NULL,
  `operation_type` VARCHAR(60) NOT NULL DEFAULT 'status_change',
  `actor_id` INT NULL DEFAULT NULL,
  `source_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `destination_location_id` INT UNSIGNED NULL DEFAULT NULL,
  `previous_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `new_custodian_id` INT UNSIGNED NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `attachment_path` VARCHAR(255) NULL DEFAULT NULL,
  `approval_ref` VARCHAR(80) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ash_asset` (`asset_id`),
  KEY `idx_ash_school` (`school_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `asset_settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `code_pattern` VARCHAR(80) NOT NULL DEFAULT 'AST-{CATEGORY}-{YEAR}-{SEQ}',
  `seq_padding` INT NOT NULL DEFAULT 6,
  `default_currency` VARCHAR(10) NOT NULL DEFAULT 'RWF',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_settings_school` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
