[PHP]
date.timezone = Africa/Kigali
memory_limit = 512M
max_execution_time = 120
post_max_size = 64M
upload_max_filesize = 64M
display_errors = Off
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED
extension_dir = "ext"

extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3

[sqlite3]
sqlite3.extension_dir =

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
