<?php

namespace App\Libraries;

/**
 * Wisdom school rules and regulations (English and Kinyarwanda)
 * used as the school conduct catalog. Each school can edit or add codes in Settings.
 */
class WisdomDisciplineCatalog
{
	/** @return list<array<string,mixed>> */
	public static function categories(): array
	{
		return [
			[
				'key' => 'uniforms',
				'en' => 'School uniforms',
				'rw' => 'Amabwiriza ajyanye n\'imyenda y\'ishuri',
				'items' => [
					[
						'no' => 1,
						'en' => 'Reducing trousers',
						'rw' => 'Kugabanya ubunini mu mugaru (15cm kuzamura) ku mapantalo kandi agasabwa kuyisubiza uko igomba kuba imeze',
						'marks' => [10, 20, 30],
						'se' => ['Buy a new one + 10 marks', 'Buy a new one + 20 marks', 'Buy a new one + 1 week home + 30 marks'],
						'sr' => ['Kugura indi + amanota 10', 'Kugura indi + amanota 20', 'Kugura indi + icyumweru 1 mu rugo + amanota 30'],
					],
					[
						'no' => 2,
						'en' => 'Reducing skirts',
						'rw' => 'Kugabanya uburebure bw’amajipo (kutaba hejuru ya 30 cm kuva ku birenge) no kugura ikwiriye',
						'marks' => [10, 20, 30],
						'se' => ['Buy a new one + 10 marks', 'Buy a new one + 20 marks', 'Buy a new one + 1 week home + 30 marks'],
						'sr' => ['Kugura indi + amanota 10', 'Kugura indi + amanota 20', 'Kugura indi + icyumweru 1 mu rugo + amanota 30'],
					],
					[
						'no' => 3,
						'en' => 'Not putting on neck-tie or socks',
						'rw' => 'Kutambara karuvati (tie) igihe cyagenywe n’amasugisi mu nkweto zifunze z’ishuri',
						'marks' => [5, 10, 20],
						'se' => ['5 marks', '10 marks', '20 marks'],
						'sr' => ['Amanota 5', 'Amanota 10', 'Amanota 20'],
					],
					[
						'no' => 4,
						'en' => 'Not putting on the right uniform of the day',
						'rw' => 'Kutambara imyenda y’ishuri yagenwe buri munsi',
						'marks' => [5, 10, 20],
						'se' => ['5 marks', '10 marks', '20 marks'],
						'sr' => ['Amanota 5', 'Amanota 10', 'Amanota 20'],
					],
					[
						'no' => 5,
						'en' => 'Not putting on school uniform during time of studying',
						'rw' => 'Kwambara imyenda itari iy’ishuri igihe cyo kwiga',
						'marks' => [10, 15, 20],
						'se' => ['10 marks', '15 marks', '20 marks'],
						'sr' => ['Amanota 10', 'Amanota 15', 'Amanota 20'],
					],
					[
						'no' => 6,
						'en' => 'Uniform or other clothes that belong to others',
						'rw' => 'Kwambara imyenda itari iye',
						'marks' => [20, 30, 40],
						'se' => ['20 marks', '30 marks', '1 week home + 40 marks'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Icyumweru 1 mu rugo + amanota 40'],
					],
					[
						'no' => 7,
						'en' => 'Caught with a telephone at school',
						'rw' => 'Gufatanwa telefoni',
						'marks' => [20, 40, 0],
						'se' => ['1 week + 20 marks', '2 weeks + 40 marks', 'Exclusion'],
						'sr' => ['Icyumweru 1 + amanota 20', 'Ibyumweru 2 + amanota 40', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'staff',
				'en' => 'Teachers, matrons and patrons',
				'rw' => 'Amabwiriza ajyanye n\'imyitwarire y\'umunyeshuri n\'umurera',
				'items' => [
					[
						'no' => 1,
						'en' => 'Disobeying a teacher or the Matron or Patron',
						'rw' => 'Gusuzugura mwarimu, cyangwa Matron/Patron',
						'marks' => [20, 40, 0],
						'se' => ['1 week + 20 marks', '2 weeks + 40 marks', '4 weeks home'],
						'sr' => ['Icyumweru 1 + amanota 20', 'Ibyumweru 2 + amanota 40', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Trying to fight a teacher or any other staff member due to your sin (s) done',
						'rw' => 'Gushaka kurwana na Mwalimu cyangwa undi Murezi (undi mukozi) bitewe n’ibyaha wakoze',
						'marks' => [20, 40, 0],
						'se' => ['2 weeks home + 20 marks', '4 weeks home + 40 marks', 'Exclusion'],
						'sr' => ['Ibyumweru 2 mu rugo + amanota 20', 'Ibyumweru 4 mu rugo + amanota 40', 'Gukurwaho'],
					],
					[
						'no' => 3,
						'en' => 'Fighting with a teacher or any other staff member',
						'rw' => 'Kurwana na Mwarimu cyangwa undi Murezi (undi mukozi) bitewe n’ibyaha wakoze',
						'marks' => [0, 0, 0],
						'se' => ['Exclusion', 'Exclusion', 'Exclusion'],
						'sr' => ['Gukurwaho', 'Gukurwaho', 'Gukurwaho'],
					],
					[
						'no' => 4,
						'en' => 'Fighting with another student at school for any reason. NO FIGHTING AT SCHOOL',
						'rw' => 'Kurwana n’abandi bana ku ishuri ku mpamvu iyo ariyo yose',
						'marks' => [20, 40, 0],
						'se' => ['2 weeks home + 20 marks', '4 weeks + 40 marks', 'Exclusion'],
						'sr' => ['Ibyumweru 2 mu rugo + amanota 20', 'Ibyumweru 4 + amanota 40', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'places',
				'en' => 'Right places and time',
				'rw' => 'Amabwiriza ajyanye n\'umunyeshuri naho agomba kuba ari',
				'items' => [
					[
						'no' => 1,
						'en' => 'Being absent in class without good reason',
						'rw' => 'Gusiba mu Ishuri nta mpamvu igaragara',
						'marks' => [20, 30, 0],
						'se' => ['20 marks', '30 marks', '1 week home'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Icyumweru 1 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Playing balls in classroom, dormitory, garden, chapel room,…',
						'rw' => 'Gukinira imipira ahabuzanijwe : mu ishuri, aho urara, mu busitani…',
						'marks' => [20, 30, 0],
						'se' => ['20 marks + pay 50,000 Frw', '30 marks + pay 50,000 Frw', '1 week + pay 50,000 Frw'],
						'sr' => ['Amanota 20 + kwishyura 50,000 Frw', 'Amanota 30 + kwishyura 50,000 Frw', 'Icyumweru 1 + kwishyura 50,000 Frw'],
					],
					[
						'no' => 3,
						'en' => 'Being absent in chapel without good reason',
						'rw' => 'Kutaboneka muri « Leadership and Governance Laboratory» nta mpamvu igaragara',
						'marks' => [20, 0, 0],
						'se' => ['20 marks', '1 week home', '2 weeks home'],
						'sr' => ['Amanota 20', 'Icyumweru 1 mu rugo', 'Ibyumweru 2 mu rugo'],
					],
					[
						'no' => 4,
						'en' => 'Being late in preparations in morning and evening',
						'rw' => 'Gukererwa mu masomo/preps nta mpamvu',
						'marks' => [10, 20, 30],
						'se' => ['10 marks', '20 marks', '30 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Amanota 30'],
					],
					[
						'no' => 5,
						'en' => 'Not being in the right place at the right time',
						'rw' => 'Kutaboneka aho ukwiriye kuba mu gihe cyagenywe nta mpamvu igaragara',
						'marks' => [10, 20, 0],
						'se' => ['10 marks', '20 marks', '2 weeks home'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Ibyumweru 2 mu rugo'],
					],
					[
						'no' => 6,
						'en' => 'To be seen in a place where you are not supposed to be',
						'rw' => 'Kuba aho utagomba kuba nta ruhushya',
						'marks' => [10, 20, 0],
						'se' => ['10 marks', '20 marks', '2 weeks home'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Ibyumweru 2 mu rugo'],
					],
				],
			],
			[
				'key' => 'classmates',
				'en' => 'Students and classmates',
				'rw' => 'Amabwiriza ajyanye n\'imyitwarire y\'umunyeshuri n\'abandi banyeshuri',
				'items' => [
					[
						'no' => 1,
						'en' => 'Fighting or insulting with other students',
						'rw' => 'Kurwana cyangwa gutukana n’abandi banyeshuri',
						'marks' => [40, 60, 0],
						'se' => ['40 marks', '60 marks', 'Exclusion'],
						'sr' => ['Amanota 40', 'Amanota 60', 'Gukurwaho'],
					],
					[
						'no' => 2,
						'en' => 'Shouting in class',
						'rw' => 'Gusakuza mu Ishuri',
						'marks' => [10, 20, 20],
						'se' => ['10 marks', '20 marks', '1 week + 20 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Icyumweru 1 + amanota 20'],
					],
					[
						'no' => 3,
						'en' => 'Shouting in dormitory',
						'rw' => 'Gusakuza muri dormitory',
						'marks' => [10, 20, 20],
						'se' => ['10 marks', '20 marks', '1 week + 20 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Icyumweru 1 + amanota 20'],
					],
					[
						'no' => 4,
						'en' => 'Creating disorder in classroom, cafeteria or in dormitory',
						'rw' => 'Gutera akaduruvayo mu ishuri, cafeteria na dormitory',
						'marks' => [20, 40, 0],
						'se' => ['1 week + 20 marks', '2 weeks + 40 marks', 'Exclusion'],
						'sr' => ['Icyumweru 1 + amanota 20', 'Ibyumweru 2 + amanota 40', 'Gukurwaho'],
					],
					[
						'no' => 5,
						'en' => 'Creating the spirit of rebellion at school',
						'rw' => 'Kugomesha abandi bana biganisha ku myigaragambyo itemewe',
						'marks' => [40, 60, 0],
						'se' => ['2 weeks + 40 marks', '4 weeks + 60 marks', 'Exclusion'],
						'sr' => ['Ibyumweru 2 + amanota 40', 'Ibyumweru 4 + amanota 60', 'Gukurwaho'],
					],
					[
						'no' => 6,
						'en' => 'Refusing to participate in hygiene activities at school',
						'rw' => 'Kwanga gufatanya n’abandi gukora isuku aho ikenewe',
						'marks' => [20, 30, 40],
						'se' => ['20 marks', '30 marks', '4 weeks + 40 marks'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Ibyumweru 4 + amanota 40'],
					],
					[
						'no' => 7,
						'en' => 'Stealing any property from any student or from the school properties. NO THIEVES AT WISDOM SCHOOL',
						'rw' => 'Gufatanwa ikintu icyo ari cyo cyose kitari icyawe',
						'marks' => [60, 0, 0],
						'se' => ['60 marks and paying back the stolen items', 'Exclusion', 'Exclusion'],
						'sr' => ['Amanota 60 no kwishyura ibyibwe', 'Gukurwaho', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'leaving',
				'en' => 'Leaving the compound and forbidden items',
				'rw' => 'Amabwiriza ajyanye no gutoroka ikigo no kuzana mu kigo ibintu bitemewe',
				'items' => [
					[
						'no' => 1,
						'en' => 'Going out of the school without permission',
						'rw' => 'Gutoroka ikigo : Gusohoka mu kigo nta ruhushya',
						'marks' => [60, 0, 0],
						'se' => ['4 weeks + 60 marks', 'Exclusion', 'Exclusion'],
						'sr' => ['Ibyumweru 4 + amanota 60', 'Gukurwaho', 'Gukurwaho'],
					],
					[
						'no' => 2,
						'en' => 'To be caught with drugs, tobacco, eats from outside the school…',
						'rw' => 'Gufatanywa ibiyobya bwenge : inzoga, itabi n’ibyo kurya bitatekewe ku ishuri',
						'marks' => [60, 0, 0],
						'se' => ['6 weeks + 60 marks', 'Exclusion', 'Exclusion'],
						'sr' => ['Ibyumweru 6 + amanota 60', 'Gukurwaho', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'property',
				'en' => 'Destroying school property',
				'rw' => 'Amabwiriza ajyanye no kwangiriza ibikoresho by\'ishuri n\'undi mutungo w\'ikigo',
				'items' => [
					[
						'no' => 1,
						'en' => 'Destroying a chair, glass,… and writing on chairs, tables and on walls',
						'rw' => 'Kwangiriza umutungo w’Ishuri : kumena intebe, ibirahuri n’ibindi, kwandika ku ntebe, ameza n’ahandi',
						'marks' => [30, 40, 0],
						'se' => ['30 marks + pay 70,000 Frw', '40 marks + pay', '4 weeks + pay'],
						'sr' => ['Amanota 30 + kwishyura 70,000 Frw', 'Amanota 40 + kwishyura', 'Ibyumweru 4 + kwishyura'],
					],
					[
						'no' => 2,
						'en' => 'Playing in the school garden',
						'rw' => 'Gukinira mu busitani bw’ikigo',
						'marks' => [30, 40, 0],
						'se' => ['30 marks + pay 30,000 Frw', '40 marks + pay', '4 weeks + pay'],
						'sr' => ['Amanota 30 + kwishyura 30,000 Frw', 'Amanota 40 + kwishyura', 'Ibyumweru 4 + kwishyura'],
					],
					[
						'no' => 3,
						'en' => 'Harvest anything from the garden without permission',
						'rw' => 'Gusarura icyo ari cyo cyose cyo mubusitani bw’ikigo',
						'marks' => [20, 40, 0],
						'se' => ['20 marks + pay 50,000 Frw', '40 marks + pay 50,000 Frw', '2 weeks + pay 50,000 Frw'],
						'sr' => ['Amanota 20 + kwishyura 50,000 Frw', 'Amanota 40 + kwishyura 50,000 Frw', 'Ibyumweru 2 + kwishyura 50,000 Frw'],
					],
					[
						'no' => 4,
						'en' => 'Destroying/misusing water, electricity or any other school properties',
						'rw' => 'Kwangiriza amazi; amashanyarazi n’ibindi bikworwa remezo by’ishuri',
						'marks' => [0, 0, 0],
						'se' => ['Pay 50,000 F + 2 weeks', 'Pay + 4 weeks', 'Pay + exclusion'],
						'sr' => ['Kwishyura 50,000 F + ibyumweru 2', 'Kwishyura + ibyumweru 4', 'Kwishyura + gukurwaho'],
					],
				],
			],
			[
				'key' => 'behavior',
				'en' => 'Student behaviour and values',
				'rw' => 'Amabwiriza ajyanye n\'indangagaciro n\'umunyeshuri we ubwe',
				'items' => [
					[
						'no' => 1,
						'en' => 'Refusing to shave/trim',
						'rw' => 'Kutagabanya umusatsi (kwanga kogoshwa) no kugaruka yogoshwe',
						'marks' => [10, 20, 0],
						'se' => ['10 marks', '20 marks', '1 week home'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Icyumweru 1 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Cheating in tests/exams',
						'rw' => 'Kwiba (gukopera) mu bizamini ibyo aribyo byose',
						'marks' => [30, 40, 50],
						'se' => ['0% and 30 marks', '0% and 40 marks', '0% and 50 marks'],
						'sr' => ['0% n\'amanota 30', '0% n\'amanota 40', '0% n\'amanota 50'],
					],
					[
						'no' => 3,
						'en' => 'Letters to girls or boys about love',
						'rw' => 'Gufatanywa inzandiko z’urukundo zitazwi n’ubuyoboz',
						'marks' => [20, 40, 30],
						'se' => ['20 marks', '40 marks', '4 weeks + 30 marks'],
						'sr' => ['Amanota 20', 'Amanota 40', 'Ibyumweru 4 + amanota 30'],
					],
					[
						'no' => 4,
						'en' => 'Doing evil things in Leadership and governance laboratory',
						'rw' => 'Gukorera muri Leadership room ibyo wishakiye ntu ruhushya',
						'marks' => [20, 30, 40],
						'se' => ['20 marks', '30 marks', '1 week home + 40 marks'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Icyumweru 1 mu rugo + amanota 40'],
					],
					[
						'no' => 5,
						'en' => 'Using vernacular',
						'rw' => 'Kudakoresha “URURIMI” aho ukwiriye kurukoresha ku Ishuri',
						'marks' => [10, 20, 30],
						'se' => ['10 marks', '20 marks', '30 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Amanota 30'],
					],
					[
						'no' => 6,
						'en' => 'Not doing what is in your interests or for others at school',
						'rw' => 'Kutubahiriza ibyo usabwa biri mu nyungu zawe cyangwa bagenzi bawe',
						'marks' => [10, 20, 30],
						'se' => ['10 marks', '20 marks', '1 week + 30 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Icyumweru 1 + amanota 30'],
					],
					[
						'no' => 7,
						'en' => 'Any behavior that leads for not studying, not being in preps and not following the school rules',
						'rw' => 'Imyitwarire yose ijyana no kudashaka kwiga, kwigomeka ku bikorwa byose bijyana no kwiga, kwiyigisha no kutumvira amabwiriza',
						'marks' => [30, 50, 20],
						'se' => ['30 marks', '50 marks', '4 weeks home + 20 marks'],
						'sr' => ['Amanota 30', 'Amanota 50', 'Ibyumweru 4 mu rugo + amanota 20'],
					],
					[
						'no' => 8,
						'en' => 'Not doing the right thing at the right time',
						'rw' => 'Gukora icyo ari cyo cyose hirya y’igihe cyagenwe',
						'marks' => [0, 0, 0],
						'se' => ['Community work', 'Community work', 'Community work'],
						'sr' => ['Gukora imirimo ifitiye abanyeshuri akamaro', 'Gukora imirimo ifitiye abanyeshuri akamaro', 'Gukora imirimo ifitiye abanyeshuri akamaro'],
					],
					[
						'no' => 9,
						'en' => 'To be caught with money',
						'rw' => 'Gufatanwa amafaranga',
						'marks' => [40, 40, 40],
						'se' => ['Confiscated and community work + 40 marks', 'Confiscated and community work + 40 marks', 'Confiscated and community work + 40 marks'],
						'sr' => ['Kwakwa ayo mafaranga agakoreshwa mu nyungu rusange z’abanyeshyuri; gukora imirimo ifitiye abanyeshuri akamaro + amanota 40', 'Kwakwa ayo mafaranga agakoreshwa mu nyungu rusange z’abanyeshyuri; gukora imirimo ifitiye abanyeshuri akamaro + amanota 40', 'Kwakwa ayo mafaranga agakoreshwa mu nyungu rusange z’abanyeshyuri; gukora imirimo ifitiye abanyeshuri akamaro + amanota 40'],
					],
					[
						'no' => 10,
						'en' => 'Any activity that doesn’t bring self respect',
						'rw' => 'Ibikorwa byose bijyanye no kutihesha agaciro: Gusuzugura Mwarimu ,“Prefects”, kwangiriza ibidukikije, kwangiriza ibyo kurya…',
						'marks' => [20, 30, 40],
						'se' => ['20 marks', '1 week + 30 marks', '4 weeks home + 40 marks'],
						'sr' => ['Amanota 20', 'Icyumweru 1 + amanota 30', 'Ibyumweru 4 mu rugo + amanota 40'],
					],
					[
						'no' => 11,
						'en' => 'Refusing to be punished or to sign in the book for your sins',
						'rw' => 'Kwanga igihano icyo ari cyose',
						'marks' => [60, 60, 60],
						'se' => ['4 weeks home + 60 marks', '4 weeks home + 60 marks', '4 weeks home + 60 marks'],
						'sr' => ['Ibyumweru 4 mu rugo + amanota 60', 'Ibyumweru 4 mu rugo + amanota 60', 'Ibyumweru 4 mu rugo + amanota 60'],
					],
				],
			],
			[
				'key' => 'repay',
				'en' => 'Paying back destroyed or missing items',
				'rw' => 'Amabwiriza ajyanye no gusubiza agaciro ibyo umunyeshuri yangirije',
				'items' => [
					[
						'no' => 1,
						'en' => 'Destroying his/her chair or a book from library',
						'rw' => 'Kwagiza intebe y’ishuri yahawe cyangwa guta igitabo cy’ishuri',
						'marks' => [10, 20, 40],
						'se' => ['Pay 70,000 Frw + 10 marks', 'Pay + 20 marks', 'Pay + 40 marks'],
						'sr' => ['Kwishyura 70,000 Frw + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 2,
						'en' => 'Destroying someone’s chair',
						'rw' => 'Kwagiza intebe y’ishuri yundi munyeshuri',
						'marks' => [20, 30, 40],
						'se' => ['Pay + 20 marks', 'Pay + 30 marks', 'Pay + 40 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 30', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 3,
						'en' => 'Destroying your classroom’s glass',
						'rw' => 'Kumena ikirahuri cy’ishuri wigamo',
						'marks' => [10, 20, 30],
						'se' => ['Pay + 10 marks', 'Pay + 20 marks', 'Pay + 30 marks'],
						'sr' => ['Kwishyura + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 30'],
					],
					[
						'no' => 4,
						'en' => 'Destroying a glass of another classroom which not yours',
						'rw' => 'Kumena ikirahuri cy’ishuri utigamo',
						'marks' => [20, 30, 40],
						'se' => ['Pay + 20 marks', 'Pay + 30 marks', 'Pay + 40 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 30', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 5,
						'en' => 'Breaking a glass at school of any building',
						'rw' => 'Kumena ikirahuri i cy’indi nyubako iyo ariyo yose yo mu kigo',
						'marks' => [20, 30, 40],
						'se' => ['Pay + 20 marks', 'Pay + 30 marks', 'Pay + 40 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 30', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 6,
						'en' => 'Misplacing someone’s cupboard key',
						'rw' => 'Guta urufunguzo rw’akabati k’undi munyeshuri',
						'marks' => [10, 20, 30],
						'se' => ['Pay + 10 marks', 'Pay + 20 marks', 'Pay + 30 marks'],
						'sr' => ['Kwishyura + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 30'],
					],
					[
						'no' => 7,
						'en' => 'Destroying any lab material',
						'rw' => 'Kwangiza igikoresho, ikinyabutabire cyo muri Laboratory',
						'marks' => [20, 30, 40],
						'se' => ['Pay + 20 marks', 'Pay + 30 marks', 'Pay + 40 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 30', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 8,
						'en' => 'Destroying any school material in any place',
						'rw' => 'Kwangiza, kumena ikindi gikoresho cy’ishuri aho cyaba giherereye hose',
						'marks' => [20, 20, 20],
						'se' => ['Pay + 20 marks', 'Pay + 20 marks', 'Pay + 20 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 20', 'Kwishyura + amanota 20'],
					],
				],
			],
			[
				'key' => 'food',
				'en' => 'Misusing food',
				'rw' => 'Amabwiriza ajyanye no kwangiriza ibyo kurya',
				'items' => [
					[
						'no' => 1,
						'en' => 'Rice',
						'rw' => 'Umuceri',
						'marks' => [20, 40, 40],
						'se' => ['50 kg + 20 marks', '50 kg + 40 marks', '50 kg + 40 marks'],
						'sr' => ['Kg 50 + amanota 20', 'Kg 50 + amanota 40', 'Kg 50 + amanota 40'],
					],
					[
						'no' => 2,
						'en' => 'Posho',
						'rw' => 'Kaunga',
						'marks' => [20, 40, 40],
						'se' => ['50 kg + 20 marks', '50 kg + 40 marks', '50 kg + 40 marks'],
						'sr' => ['Kg 50 + amanota 20', 'Kg 50 + amanota 40', 'Kg 50 + amanota 40'],
					],
					[
						'no' => 3,
						'en' => 'Irish Potatoes',
						'rw' => 'Ibirayi',
						'marks' => [0, 0, 0],
						'se' => ['50 kg', '50 kg', '50 kg'],
						'sr' => ['Kg 50', 'Kg 50', 'Kg 50'],
					],
					[
						'no' => 4,
						'en' => 'Matoke',
						'rw' => 'Matoke',
						'marks' => [0, 0, 0],
						'se' => ['50 kg', '50 kg', '50 kg'],
						'sr' => ['Kg 50', 'Kg 50', 'Kg 50'],
					],
					[
						'no' => 5,
						'en' => 'Sweet Potatoes',
						'rw' => 'Ibijumba',
						'marks' => [0, 0, 0],
						'se' => ['50 kg', '50 kg', '50 kg'],
						'sr' => ['Kg 50', 'Kg 50', 'Kg 50'],
					],
					[
						'no' => 6,
						'en' => 'Beans',
						'rw' => 'Ibishyimbo',
						'marks' => [0, 0, 0],
						'se' => ['50 kg', '50 kg', '50 kg'],
						'sr' => ['Kg 50', 'Kg 50', 'Kg 50'],
					],
					[
						'no' => 7,
						'en' => 'Peas',
						'rw' => 'Amashyaza',
						'marks' => [0, 0, 0],
						'se' => ['50 kg', '50 kg', '50 kg'],
						'sr' => ['Kg 50', 'Kg 50', 'Kg 50'],
					],
					[
						'no' => 8,
						'en' => 'Porridge',
						'rw' => 'Igikoma',
						'marks' => [0, 0, 0],
						'se' => ['50 kg mixed maize, sorghum, wheat, soya and uburo', '50 kg mixed maize, sorghum, wheat, soya and uburo', '50 kg mixed maize, sorghum, wheat, soya and uburo'],
						'sr' => ['Kg 50 by\'ibigori, amasaka, ingano, soya na uburo ivanze', 'Kg 50 by\'ibigori, amasaka, ingano, soya na uburo ivanze', 'Kg 50 by\'ibigori, amasaka, ingano, soya na uburo ivanze'],
					],
					[
						'no' => 9,
						'en' => 'Vegetables',
						'rw' => 'Imboga-rwatsi',
						'marks' => [20, 40, 40],
						'se' => ['10,000 Fr + 20 marks', '20,000 Frw + 40 marks', '30,000 Frw + 40 marks'],
						'sr' => ['10,000 Fr + amanota 20', '20,000 Frw + amanota 40', '30,000 Frw + amanota 40'],
					],
					[
						'no' => 10,
						'en' => 'Milk',
						'rw' => 'Amata',
						'marks' => [20, 40, 40],
						'se' => ['20,000 Frw + 20 marks', '40,000 Frw + 40 marks', '50,000 Frw + 40 marks'],
						'sr' => ['20,000 Frw + amanota 20', '40,000 Frw + amanota 40', '50,000 Frw + amanota 40'],
					],
				],
			],
		];
	}
}
