<?php

namespace App\Libraries;

/**
 * Wisdom 2026 discipline laws (Amabwiriza ya Discipline) used as the default
 * school conduct catalog. Each school can edit or add codes in Settings.
 */
class WisdomDisciplineCatalog
{
	/** @return list<array<string,mixed>> */
	public static function categories(): array
	{
		return [
			[
				'key' => 'uniforms',
				'en' => 'School uniforms',
				'rw' => 'Amabwiriza ajyanye n\'imyenda y\'ishuri',
				'items' => [
					[
						'no' => 1,
						'en' => 'Reducing trousers (15cm raise) and being required to restore the correct size',
						'rw' => 'Kugabanya ubunini mu mugaru (15cm kuzamura) ku mapantalo kandi agasabwa kuyisubiza uko igomba kuba imeze',
						'marks' => [0, 0, 0],
						'se' => ['Buy a new one', 'Buy a new one + 2 weeks home', 'Buy a new one + 1 month home'],
						'sr' => ['Kugura indi', 'Kugura indi + 2 weeks home', 'Kugura indi + 1 month home'],
					],
					[
						'no' => 2,
						'en' => 'Reducing skirts (not above 30cm from the feet) and buying a proper one',
						'rw' => 'Kugabanya uburebure bw\'amajipo (kutaba hejuru ya 30 cm kuva ku birenge) no kugura ikwiriye',
						'marks' => [0, 0, 0],
						'se' => ['Buy a new one', 'Buy a new one + 2 weeks home', 'Buy a new one + 1 month home'],
						'sr' => ['Kugura indi', 'Kugura indi + 2 weeks', 'Kugura indi + 1 month home'],
					],
					[
						'no' => 3,
						'en' => 'Not putting on neck-tie or school socks when required',
						'rw' => 'Kutambara karuvati igihe cyagenywe n\'amasugisi mu nkweto zifunze z\'ishuri',
						'marks' => [10, 20, 40],
						'se' => ['10 marks', '20 marks', '40 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Amanota 40'],
					],
					[
						'no' => 4,
						'en' => 'Not putting on the right uniform of the day',
						'rw' => 'Kutambara imyenda y\'ishuri yagenwe buri munsi',
						'marks' => [10, 20, 40],
						'se' => ['10 marks', '20 marks', '40 marks'],
						'sr' => ['Amanota 10', 'Amanota 20', 'Amanota 40'],
					],
					[
						'no' => 5,
						'en' => 'Not putting on school uniform during studying time',
						'rw' => 'Kwambara imyenda itari iy\'ishuri igihe cyo kwiga',
						'marks' => [20, 30, 40],
						'se' => ['20 marks', '30 marks', '40 marks'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Amanota 40'],
					],
					[
						'no' => 6,
						'en' => 'Wearing uniform or other clothes that belong to others',
						'rw' => 'Kwambara imyenda itari iye',
						'marks' => [30, 40, 0],
						'se' => ['30 marks', '40 marks', '1 month home'],
						'sr' => ['Amanota 30', 'Amanota 40', 'Ukwezi 1 mu rugo'],
					],
					[
						'no' => 7,
						'en' => 'Caught with a telephone at school',
						'rw' => 'Gufatanwa telefoni',
						'marks' => [0, 0, 0],
						'se' => ['6 weeks home', 'Exclusion', 'Exclusion'],
						'sr' => ['Ibyumweru 6 mu rugo', 'Gukurwaho', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'staff',
				'en' => 'Teachers, matrons and patrons',
				'rw' => 'Amabwiriza ajyanye n\'imyitwarire y\'umunyeshuri n\'umurera',
				'items' => [
					[
						'no' => 1,
						'en' => 'Disobeying a teacher, matron or patron',
						'rw' => 'Gusuzugura mwarimu, cyangwa Matron/Patron',
						'marks' => [0, 0, 0],
						'se' => ['1 week home', '2 weeks home', '4 weeks home'],
						'sr' => ['Icyumweru 1 mu rugo', 'Ibyumweru 2 mu rugo', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Trying to fight a teacher or any other staff member',
						'rw' => 'Gushaka kurwana na Mwalimu cyangwa undi murezi (undi mukozi)',
						'marks' => [0, 0, 0],
						'se' => ['2 weeks home', '4 weeks home', 'Exclusion'],
						'sr' => ['Ibyumweru 2 mu rugo', 'Ibyumweru 4 mu rugo', 'Gukurwaho'],
					],
					[
						'no' => 3,
						'en' => 'Fighting with a teacher or any other staff member',
						'rw' => 'Kurwana na Mwarimu cyangwa undi murezi (undi mukozi)',
						'marks' => [0, 0, 0],
						'se' => ['Exclusion', 'Exclusion', 'Exclusion'],
						'sr' => ['Gukurwaho', 'Gukurwaho', 'Gukurwaho'],
					],
					[
						'no' => 4,
						'en' => 'Fighting with another student at school for any reason',
						'rw' => 'Kurwana n\'abandi bana ku ishuri ku mpamvu iyo ariyo yose',
						'marks' => [0, 0, 0],
						'se' => ['2 weeks home', '4 weeks home', 'Exclusion'],
						'sr' => ['Ibyumweru 2 mu rugo', 'Ibyumweru 4 mu rugo', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'places',
				'en' => 'Right places and time',
				'rw' => 'Amabwiriza ajyanye n\'umunyeshuri naho agomba kuba ari',
				'items' => [
					[
						'no' => 1,
						'en' => 'Being absent in class without a good reason',
						'rw' => 'Gusiba mu Ishuri nta mpamvu igaragara',
						'marks' => [30, 40, 0],
						'se' => ['30 marks', '40 marks', '2 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 40', 'Ibyumweru 2 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Playing balls in classroom, dormitory, garden or chapel',
						'rw' => 'Gukinira imipira ahabuzanijwe: mu ishuri, aho urara, mu busitani...',
						'marks' => [30, 40, 0],
						'se' => ['30 marks + pay 50,000 Frw', '40 marks + pay 50,000 Frw', '2 weeks home + pay 50,000 Frw'],
						'sr' => ['Amanota 30 + kwishyura 50,000 Frw', 'Amanota 40 + kwishyura 50,000 Frw', 'Ibyumweru 2 + kwishyura 50,000 Frw'],
					],
					[
						'no' => 3,
						'en' => 'Being absent in chapel without a good reason',
						'rw' => 'Kutaboneka muri chapel nta mpamvu igaragara',
						'marks' => [40, 0, 0],
						'se' => ['40 marks', '2 weeks home', '4 weeks home'],
						'sr' => ['Amanota 40', 'Ibyumweru 2 mu rugo', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 4,
						'en' => 'Being late in morning or evening preparations without a reason',
						'rw' => 'Gukererwa mu masomo/preps nta mpamvu',
						'marks' => [20, 30, 0],
						'se' => ['20 marks', '30 marks', '1 week home'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Icyumweru 1 mu rugo'],
					],
					[
						'no' => 5,
						'en' => 'Not being in the right place at the right time',
						'rw' => 'Kutaboneka aho ukwiriye kuba mu gihe cyagenywe nta mpamvu igaragara',
						'marks' => [40, 50, 0],
						'se' => ['40 marks', '50 marks', '4 weeks home'],
						'sr' => ['Amanota 40', 'Amanota 50', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 6,
						'en' => 'Being seen in a place where you are not supposed to be',
						'rw' => 'Kuba aho utagomba kuba nta ruhushya',
						'marks' => [40, 60, 0],
						'se' => ['40 marks', '60 marks', 'Exclusion'],
						'sr' => ['Amanota 40', 'Amanota 60', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'classmates',
				'en' => 'Students and classmates',
				'rw' => 'Amabwiriza ajyanye n\'imyitwarire y\'umunyeshuri n\'abandi banyeshuri',
				'items' => [
					[
						'no' => 1,
						'en' => 'Fighting or insulting other students',
						'rw' => 'Kurwana cyangwa gutukana n\'abandi banyeshuri',
						'marks' => [40, 60, 0],
						'se' => ['40 marks', '60 marks', 'Exclusion'],
						'sr' => ['Amanota 40', 'Amanota 60', 'Gukurwaho'],
					],
					[
						'no' => 2,
						'en' => 'Shouting in class',
						'rw' => 'Gusakuza mu Ishuri',
						'marks' => [30, 40, 0],
						'se' => ['30 marks', '40 marks', '2 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 40', 'Ibyumweru 2'],
					],
					[
						'no' => 3,
						'en' => 'Shouting in dormitory',
						'rw' => 'Gusakuza muri dormitory',
						'marks' => [30, 40, 0],
						'se' => ['30 marks', '40 marks', '2 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 40', 'Ibyumweru 2'],
					],
					[
						'no' => 4,
						'en' => 'Creating disorder in classroom, cafeteria or dormitory',
						'rw' => 'Gutera akaduruvayo mu ishuri, cafeteria na dormitory',
						'marks' => [0, 0, 0],
						'se' => ['2 weeks home', '4 weeks home', 'Exclusion'],
						'sr' => ['Ibyumweru 2', 'Ibyumweru 4', 'Gukurwaho'],
					],
					[
						'no' => 5,
						'en' => 'Creating the spirit of rebellion at school',
						'rw' => 'Kugomesha abandi bana biganisha ku myigaragambyo itemewe',
						'marks' => [0, 0, 0],
						'se' => ['4 weeks home', '5 weeks home', 'Exclusion'],
						'sr' => ['Ibyumweru 4', 'Ibyumweru 5', 'Gukurwaho'],
					],
					[
						'no' => 6,
						'en' => 'Refusing to participate in hygiene activities at school',
						'rw' => 'Kwanga gufatanya n\'abandi gukora isuku aho ikenewe',
						'marks' => [30, 50, 0],
						'se' => ['30 marks', '50 marks', '4 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 50', 'Ibyumweru 4'],
					],
					[
						'no' => 7,
						'en' => 'Stealing any property from a student or the school',
						'rw' => 'Gufatanwa ikintu icyo ari cyo cyose kitari icyawe',
						'marks' => [60, 0, 0],
						'se' => ['60 marks and pay back stolen items', 'Exclusion', 'Exclusion'],
						'sr' => ['Amanota 60 no kwishyura ibyibwe', 'Gukurwaho', 'Gukurwaho'],
					],
					[
						'no' => 8,
						'en' => 'Putting on clothes which are not his/hers',
						'rw' => 'Kwambara imyambaro y\'undi munyeshuri',
						'marks' => [40, 0, 0],
						'se' => ['40 marks', '2 weeks home', '4 weeks home'],
						'sr' => ['Amanota 40', 'Ibyumweru 2 mu rugo', 'Ibyumweru 4 mu rugo'],
					],
				],
			],
			[
				'key' => 'leaving',
				'en' => 'Leaving the compound and forbidden items',
				'rw' => 'Amabwiriza ajyanye no gutoroka ikigo no kuzana mu kigo ibintu bitemewe',
				'items' => [
					[
						'no' => 1,
						'en' => 'Going out of the school without permission',
						'rw' => 'Gutoroka ikigo: gusohoka mu kigo nta ruhushya',
						'marks' => [0, 0, 0],
						'se' => ['4 weeks home', 'Exclusion', 'Exclusion'],
						'sr' => ['Ibyumweru 4 mu rugo', 'Gukurwaho', 'Gukurwaho'],
					],
					[
						'no' => 2,
						'en' => 'Caught with drugs, tobacco or food from outside the school',
						'rw' => 'Gufatanywa ibiyobya bwenge: inzoga, itabi n\'ibyo kurya bitatekewe ku ishuri',
						'marks' => [0, 0, 0],
						'se' => ['6 weeks home', 'Exclusion', 'Exclusion'],
						'sr' => ['Ibyumweru 6 mu rugo', 'Gukurwaho', 'Gukurwaho'],
					],
				],
			],
			[
				'key' => 'property',
				'en' => 'Destroying school property',
				'rw' => 'Amabwiriza ajyanye no kwangiriza ibikoresho by\'ishuri n\'undi mutungo w\'ikigo',
				'items' => [
					[
						'no' => 1,
						'en' => 'Destroying a chair, glass or writing on chairs, tables and walls',
						'rw' => 'Kwangiriza umutungo w\'Ishuri: kumena intebe, ibirahuri n\'ibindi, kwandika ku ntebe, ameza n\'ahandi',
						'marks' => [30, 40, 0],
						'se' => ['30 marks + pay 70,000 Frw', '40 marks + payment', '4 weeks home + payment'],
						'sr' => ['Amanota 30 + kwishyura 70,000 Frw', 'Amanota 40 + kwishyura', 'Ibyumweru 4 + kwishyura'],
					],
					[
						'no' => 2,
						'en' => 'Playing in the school garden',
						'rw' => 'Gukinira mu busitani bw\'ikigo',
						'marks' => [30, 40, 0],
						'se' => ['30 marks + pay 25,000 Frw', '40 marks + payment', '4 weeks home + payment'],
						'sr' => ['Amanota 30 + kwishyura 25,000 Frw', 'Amanota 40 + kwishyura', 'Ibyumweru 4 + kwishyura'],
					],
					[
						'no' => 3,
						'en' => 'Harvesting anything from the garden without permission',
						'rw' => 'Gusarura icyo ari cyo cyose cyo mu busitani bw\'ikigo',
						'marks' => [20, 40, 0],
						'se' => ['20 marks + pay 25,000 Frw', '40 marks + pay 25,000 Frw', '2 weeks home + pay 25,000 Frw'],
						'sr' => ['Amanota 20 + kwishyura 25,000 Frw', 'Amanota 40 + kwishyura 25,000 Frw', 'Ibyumweru 2 + kwishyura 25,000 Frw'],
					],
					[
						'no' => 4,
						'en' => 'Destroying or misusing water, electricity or other school infrastructure',
						'rw' => 'Kwangiriza amazi, amashanyarazi n\'ibindi bikworwa remezo by\'ishuri',
						'marks' => [0, 0, 0],
						'se' => ['Pay 25,000 Frw + 2 weeks home', 'Payment + 4 weeks home', 'Payment + exclusion'],
						'sr' => ['Kwishyura 25,000 Frw + ibyumweru 2', 'Kwishyura + ibyumweru 4', 'Kwishyura + gukurwaho'],
					],
				],
			],
			[
				'key' => 'behavior',
				'en' => 'Student behaviour and values',
				'rw' => 'Amabwiriza ajyanye n\'indangagaciro n\'umunyeshuri we ubwe',
				'items' => [
					[
						'no' => 1,
						'en' => 'Refusing to shave or trim and returning unshaved',
						'rw' => 'Kutagabanya umusatsi (kwanga kogoshwa) no kugaruka yogoshwe',
						'marks' => [30, 50, 0],
						'se' => ['30 marks', '50 marks', '6 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 50', 'Ibyumweru 6 mu rugo'],
					],
					[
						'no' => 2,
						'en' => 'Cheating in tests or exams',
						'rw' => 'Kwiba (gukopera) mu bizamini ibyo aribyo byose',
						'marks' => [30, 40, 50],
						'se' => ['0% and 30 marks', '0% and 40 marks', '0% and 50 marks'],
						'sr' => ['0% n\'amanota 30', '0% n\'amanota 40', '0% n\'amanota 50'],
					],
					[
						'no' => 3,
						'en' => 'Caught with love letters not known by leadership',
						'rw' => 'Gufatanywa inzandiko z\'urukundo zitazwi n\'ubuyobozi',
						'marks' => [30, 40, 0],
						'se' => ['30 marks', '40 marks', '4 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 40', 'Ibyumweru 4'],
					],
					[
						'no' => 4,
						'en' => 'Doing forbidden things in leadership or chapel room without permission',
						'rw' => 'Gukorera muri Leadership room ibyo wishakiye nta ruhushya',
						'marks' => [20, 30, 0],
						'se' => ['20 marks', '30 marks', '1 week home'],
						'sr' => ['Amanota 20', 'Amanota 30', 'Icyumweru 1 mu rugo'],
					],
					[
						'no' => 5,
						'en' => 'Not using the required language at school',
						'rw' => 'Kudakoresha URURIMI aho ukwiriye kurukoresha ku Ishuri',
						'marks' => [40, 50, 0],
						'se' => ['40 marks', '50 marks', '2 weeks home'],
						'sr' => ['Amanota 40', 'Amanota 50', 'Ibyumweru 2 mu rugo'],
					],
					[
						'no' => 6,
						'en' => 'Not doing what is required in your interest or for others',
						'rw' => 'Kutubahiriza ibyo usabwa biri mu nyungu zawe cyangwa bagenzi bawe',
						'marks' => [20, 40, 0],
						'se' => ['20 marks', '40 marks', '2 weeks home'],
						'sr' => ['Amanota 20', 'Amanota 40', 'Ibyumweru 2'],
					],
					[
						'no' => 7,
						'en' => 'Any behaviour of refusing to study, missing preps or not following school rules',
						'rw' => 'Imyitwarire yose ijyana no kudashaka kwiga, kwigomeka ku bikorwa byose bijyana no kwiga, kwiyigisha no kutumvira amabwiriza',
						'marks' => [30, 50, 0],
						'se' => ['30 marks', '50 marks', '4 weeks home'],
						'sr' => ['Amanota 30', 'Amanota 50', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 8,
						'en' => 'Not doing the right thing at the right time',
						'rw' => 'Gukora icyo ari cyo cyose hirya y\'igihe cyagenwe',
						'marks' => [0, 0, 0],
						'se' => ['Community work', 'Community work', 'Community work'],
						'sr' => ['Gukora imirimo ifitiye abanyeshuri akamaro', 'Imirimo rusange', 'Imirimo rusange'],
					],
					[
						'no' => 9,
						'en' => 'Caught with money',
						'rw' => 'Gufatanwa amafaranga',
						'marks' => [0, 0, 0],
						'se' => ['Money confiscated for student community use + community work', 'Same', 'Same'],
						'sr' => ['Kwakwa ayo mafaranga agakoreshwa mu nyungu rusange + imirimo rusange', 'Kimwe', 'Kimwe'],
					],
					[
						'no' => 10,
						'en' => 'Any activity that does not bring self-respect (disobeying teachers or prefects, destroying environment or food)',
						'rw' => 'Ibikorwa byose bijyanye no kutihesha agaciro: gusuzugura Mwarimu, Prefects, kwangiriza ibidukikije, kwangiriza ibyo kurya',
						'marks' => [0, 0, 0],
						'se' => ['2 weeks home', '3 weeks home', '4 weeks home'],
						'sr' => ['Ibyumweru 2', 'Ibyumweru 3', 'Ibyumweru 4 mu rugo'],
					],
					[
						'no' => 11,
						'en' => 'Refusing to be punished or to sign in the book for the offence',
						'rw' => 'Kwanga igihano icyo ari cyose',
						'marks' => [0, 0, 0],
						'se' => ['4 weeks home', '4 weeks home', '4 weeks home'],
						'sr' => ['Ibyumweru 4 mu rugo', 'Ibyumweru 4 mu rugo', 'Ibyumweru 4 mu rugo'],
					],
				],
			],
			[
				'key' => 'repay',
				'en' => 'Paying back destroyed or missing items',
				'rw' => 'Amabwiriza ajyanye no gusubiza agaciro ibyo umunyeshuri yangirije',
				'items' => [
					[
						'no' => 1,
						'en' => 'Destroying the chair given to him/her or losing a library book',
						'rw' => 'Kwagiza intebe y\'ishuri yahawe cyangwa guta igitabo cy\'ishuri',
						'marks' => [10, 20, 50],
						'se' => ['Pay 70,000 Frw + 10 marks', 'Payment + 20 marks', 'Payment + 50 marks'],
						'sr' => ['Kwishyura 70,000 Frw + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 50'],
					],
					[
						'no' => 2,
						'en' => 'Destroying another student\'s chair',
						'rw' => 'Kwagiza intebe y\'ishuri y\'undi munyeshuri',
						'marks' => [15, 30, 60],
						'se' => ['Payment + 15 marks', 'Payment + 30 marks', 'Payment + 60 marks'],
						'sr' => ['Kwishyura + amanota 15', 'Kwishyura + amanota 30', 'Kwishyura + amanota 60'],
					],
					[
						'no' => 3,
						'en' => 'Breaking a glass of his/her own classroom',
						'rw' => 'Kumena ikirahuri cy\'ishuri wigamo',
						'marks' => [10, 20, 30],
						'se' => ['Payment + 10 marks', 'Payment + 20 marks', 'Payment + 30 marks'],
						'sr' => ['Kwishyura + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 30'],
					],
					[
						'no' => 4,
						'en' => 'Breaking a glass of another classroom',
						'rw' => 'Kumena ikirahuri cy\'ishuri utigamo',
						'marks' => [15, 30, 45],
						'se' => ['Payment + 15 marks', 'Payment + 30 marks', 'Payment + 45 marks'],
						'sr' => ['Kwishyura + amanota 15', 'Kwishyura + amanota 30', 'Kwishyura + amanota 45'],
					],
					[
						'no' => 5,
						'en' => 'Breaking a glass of any other school building',
						'rw' => 'Kumena ikirahuri cy\'indi nyubako iyo ariyo yose yo mu kigo',
						'marks' => [20, 30, 40],
						'se' => ['Payment + 20 marks', 'Payment + 30 marks', 'Payment + 40 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 30', 'Kwishyura + amanota 40'],
					],
					[
						'no' => 6,
						'en' => 'Misplacing another student\'s cupboard key',
						'rw' => 'Guta urufunguzo rw\'akabati k\'undi munyeshuri',
						'marks' => [10, 20, 30],
						'se' => ['Payment + 10 marks', 'Payment + 20 marks', 'Payment + 30 marks'],
						'sr' => ['Kwishyura + amanota 10', 'Kwishyura + amanota 20', 'Kwishyura + amanota 30'],
					],
					[
						'no' => 7,
						'en' => 'Destroying any laboratory material',
						'rw' => 'Kwangiza igikoresho, ikinyabutabire cyo muri Laboratory',
						'marks' => [0, 0, 0],
						'se' => ['Payment', 'Payment', 'Payment'],
						'sr' => ['Kwishyura', 'Kwishyura', 'Kwishyura'],
					],
					[
						'no' => 8,
						'en' => 'Destroying any other school material anywhere',
						'rw' => 'Kwangiza, kumena ikindi gikoresho cy\'ishuri aho cyaba giherereye hose',
						'marks' => [20, 20, 20],
						'se' => ['Payment + 20 marks', 'Payment + 20 marks', 'Payment + 20 marks'],
						'sr' => ['Kwishyura + amanota 20', 'Kwishyura + amanota 20', 'Kwishyura + amanota 20'],
					],
				],
			],
			[
				'key' => 'food',
				'en' => 'Misusing food',
				'rw' => 'Amabwiriza ajyanye no kwangiriza ibyo kurya',
				'items' => [
					[
						'no' => 1,
						'en' => 'Rice (Umuceri)',
						'rw' => 'Umuceri',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 2,
						'en' => 'Posho / Kaunga',
						'rw' => 'Posho/Kaunga',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 3,
						'en' => 'Irish potatoes (Ibirayi)',
						'rw' => 'Ibirayi',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 4,
						'en' => 'Matoke',
						'rw' => 'Matoke',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 5,
						'en' => 'Sweet potatoes (Ibijumba)',
						'rw' => 'Ibijumba',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 6,
						'en' => 'Beans (Ibishyimbo)',
						'rw' => 'Ibishyimbo',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 7,
						'en' => 'Peas (Amashyaza)',
						'rw' => 'Amashyaza',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 8,
						'en' => 'Porridge (Igikoma)',
						'rw' => 'Igikoma',
						'marks' => [0, 10, 30],
						'se' => ['Replace 50 kg mixed flour', '50 kg and 10 marks', '50 kg and 30 marks'],
						'sr' => ['Gusubiza kg 50 z\'ifumbire', 'Kg 50 n\'amanota 10', 'Kg 50 n\'amanota 30'],
					],
					[
						'no' => 9,
						'en' => 'Vegetables (Imboga)',
						'rw' => 'Imboga-rwatsi',
						'marks' => [0, 0, 0],
						'se' => ['Pay 10,000 Frw', 'Pay 20,000 Frw', 'Pay 30,000 Frw'],
						'sr' => ['Kwishyura 10,000 Frw', 'Kwishyura 20,000 Frw', 'Kwishyura 30,000 Frw'],
					],
					[
						'no' => 10,
						'en' => 'Milk (Amata)',
						'rw' => 'Amata',
						'marks' => [0, 0, 0],
						'se' => ['Pay 20,000 Frw', 'Pay 40,000 Frw', 'Pay 50,000 Frw'],
						'sr' => ['Kwishyura 20,000 Frw', 'Kwishyura 40,000 Frw', 'Kwishyura 50,000 Frw'],
					],
				],
			],
		];
	}
}
